In [3]:
import numpy as np

"""
某周天气最高温：28，30，29，31，32，30，29
求平均气温，最高最低气温
求超过30°的天数
"""

'\n某周天气最高温：28，30，29，31，32，30，29\n求平均气温，最高最低气温\n求超过30°的天数\n'

In [7]:
temp = np.array([28,30,29,31,32,30,29])
print(np.max(temp))
print(np.min(temp))
print(np.mean(temp))
print(len(temp[temp>30]))


32
28
29.857142857142858
2


In [ ]:
'''
某班级5个学生的成绩L:85,90,78,92,88
计算成绩的平均分，中位数和标准差
将成绩转换成十分制（假设满分10）
'''

In [12]:
score = np.array([85,90,78,92,88])
print(np.mean(score))
print(np.median(score))
print(np.std(score))#标准差


86.6
88.0
4.882622246293481


In [ ]:
'''
矩阵A = [[1,2],[3,4]]  B=[[5,6],[7,8]]
计算A+B A*B
A,B的矩阵乘法
'''

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
'''
生成一个（3，4）的随机整数数组范围0-10
计算每列max，每行min
将数组中的所有奇数替换成-1
'''

In [48]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print("原始数组：")
print(arr)
print("每列最大值：")
print(arr.max(axis=0))
print("每行最小值：")
print(arr.min(axis=1))
print("奇数替换为-1：")
print(np.where(arr % 2 == 1,-1,arr))

原始数组：
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列最大值：
[7 9 7 6]
每行最小值：
[0 3 2]
奇数替换为-1：
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
'''
创建一个1-12一维数组，并转换成（3，4）的二维数组
计算每行的和，每列的平均值
将数组展平为一维数组
'''

In [60]:
arr1 = np.arange(1,13)
arr2 = arr1.reshape(3,4)
print('arr1:',arr1)
print('arr2:')
print(arr2)
print(arr2.sum(axis=1))
print(arr2.mean(axis=0))
arr3 = arr2.reshape(12)
print('arr3:',arr3)

arr1: [ 1  2  3  4  5  6  7  8  9 10 11 12]
arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
arr3: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [65]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print('arr:')
print(arr)
print('arr1:')
print(arr[arr>10])
print('arr2:')
print(np.where(arr>10,0,arr))

arr:
[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
arr1:
[12 15 19 18 12 14 17 13 19 16 19]
arr2:
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [72]:
arr = np.array([120,135,110,125,130,140])
print('arr:')
print(np.sum(arr))
print(arr.mean())
print(arr.var())
print(np.argmax(arr)+1)
print(np.argmin(arr)+1)

arr:
760
126.66666666666667
97.22222222222223
6
3
